- name: Install required packages
  become: true
  package:
    update_cache: true
    name:
      - gdisk
      - kpartx
      - dosfstools
      - e2fsprogs
      - gnupg
      #- qemu-utils
      - python3-lxml
      #- grub-efi-amd64
      #- grub-efi-amd64-bin
      #- grub-common
      #- isolinux
      - syslinux
      - python3-requests
      - rsync
      - unzip
      #- zlib1g-dev
      - zlib-devel
      - squashfs-tools
      - xorriso
    state: present
